services:
    cryonighter.formula_doctrine.metadata_factory:
        class: Cryonighter\FormulaDoctrine\Metadata\FormulaMetadataFactory
        public: false

    cryonighter.formula_doctrine.metadata_registry:
        class: Cryonighter\FormulaDoctrine\Metadata\FormulaMetadataRegistry
        public: true
        arguments:
            - '@cryonighter.formula_doctrine.metadata_factory'

    cryonighter.formula_doctrine.configurator:
        class: Cryonighter\FormulaDoctrine\Configuration\FormulaDoctrineConfigurator
        public: false
        arguments:
            - '@cryonighter.formula_doctrine.metadata_registry'

    cryonighter.formula_doctrine.listener.load_class_metadata:
        class: Cryonighter\FormulaDoctrine\EventListener\LoadClassMetadataListener
        public: false
        arguments:
            - '@cryonighter.formula_doctrine.metadata_registry'
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata, priority: 10 }

    cryonighter.formula_doctrine.listener.post_generate_schema:
        class: Cryonighter\FormulaDoctrine\EventListener\PostGenerateSchemaListener
        public: false
        arguments:
            - '@cryonighter.formula_doctrine.metadata_registry'
        tags:
            - { name: doctrine.event_listener, event: postGenerateSchema }

    cryonighter.formula_doctrine.dbal_middleware:
        class: Cryonighter\FormulaDoctrine\DBAL\FormulaMiddleware
        public: false
        arguments:
            - '@cryonighter.formula_doctrine.metadata_registry'
        tags:
            - { name: doctrine.middleware }

    Cryonighter\FormulaDoctrine\Query\FormulaSqlWalker:
        autowire: false
        autoconfigure: false
        public: false